name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Release"
    env:
      NODE_VERSION: '14.x'                # set this to the node version to use

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Update npm
      run: |
        npm install npm@latest

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Build and Publish Nuget Packages
      run: |
        nuget pack nuspec\EventStoreProjections.nuspec -Properties version=${{ steps.get_version.outputs.VERSION }} -OutputDirectory Nugets
        dotnet nuget push Nugets/EventStoreProjections.${{ steps.get_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.PRIVATEFEED_APIKEY }} --source ${{ secrets.PRIVATEFEED_URL }}

      
       
